---
title: "Performance of Rookie Can Predict Price of Their RC based Prizm Cards"
subtitle: "My subtitle if needed"
author: 
  - Harrison Huang
thanks: "Code and data are available at: https://github.com/lemonface88/NBA"
date: today 
date-format: long
abstract: "Collecting and investing in cards has been relevant for a while now. There are complex factors that contribute to the price fluxation of these cards. This analysis will use player statistics to create a model to try to grasp possible future price trends of the card. A xxx model was used in this analysis. The results indicated that xxx is a strong indicator of the price fluctuation of potential future prices of the rookie card."
format: pdf
number-sections: true
bibliography: references.bib
---


# Introduction

Collectible cards such as Pokemon, Yu-Gi-Oh! cards, and Sports cards still exist and are relevant in our world. In the digitized world we live in today, these physical cards are often forgotten. We have also heard wild stories about specific Pokemon cards selling for millions of dollars, the same applies to other collectible cards. NBA basketball cards have gained significant popularity in recent years. Apart from being collector's items, they have also become a form of investment for some individuals. 

Many factors go into the valuation of a basketball card. Some example factors include the rarity of the card, the performance and popularity of the player, which series it comes from, and the condition of the card. Each year, the cards are updated and RC labeled cards are labeled on the players that are rookies for that year. These RC-labeled cards are only printed in that specific year and are usually the most sought-after cards among collectors. The specific stats of each player such as points per game, rebounds, and turnover also dictate the valuation of their rookie cards. The complexity of these elements often makes it difficult to predict the future value of the card.

This analysis finds that….



	In Section 2 of the paper, the source and datasets are discussed. Strengths and weaknesses, methods of collection, and terminologies will be explored. Section 3 of the paper will incorporate a model aiming to use player statistics to predict the price trend of the card. Section 4 will then look at the results from the model. Lastly, section 5 will be a reflection about possible steps and the discussion of the strengths and weaknesses of this analysis. 




```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
```



# Data

Talk more about it. Data used here are unmanipulated data, simply created by graph functions with the data sets.



# Model

The goal of our modelling strategy is twofold. Firstly,...



## Model set-up

Define $y_i$ as the number of seconds that the plane remained aloft. Then $\beta_i$ is the wing width and $\gamma_i$ is the wing length, both measured in millimeters.  

\begin{align} 
y_i|\mu_i, \sigma &\sim \mbox{Normal}(\mu_i, \sigma) \\
\mu_i &= \alpha + \beta_i + \gamma_i\\
\alpha &\sim \mbox{Normal}(0, 2.5) \\
\beta &\sim \mbox{Normal}(0, 2.5) \\
\gamma &\sim \mbox{Normal}(0, 2.5) \\
\sigma &\sim \mbox{Exponential}(1)
\end{align}

We run the model in R [@citeR] using the `rstanarm` package of @rstanarm. We use the default priors from `rstanarm`.


### Model justification

We expect a positive relationship between the size of the wings and time spent aloft. In particular...

We can use maths by including latex between dollar signs, for instance $\theta$.


# Results



# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.



\newpage

\appendix

# Appendix




\newpage


# References


